### ISSUE TITLE
CalendarEvent.ExternalID changes

### ISSUE THREAD

**Issue by Toemsel** [TheAlmightyBob/Calendars#37]
1. Create a CalendarEvent and assign a ExternalID (Lets say 123123)
2. AddOrUpdateEventAsync with the CalendarEvent from step 1

3. GetEventByIdAsync with the ExternalID from step 1. => No result
4. GetEventsAsync with a range including CalendarEvent from step 1. In the list, the Event has a different ExternalID (in this case, 12)

Expected behaviour? How am I able to retrieve an Event with an ID I assigned before?
Am I doing this wrong or is it a Bug?

**Comment by TheAlmightyBob** [comment]
That is expected behavior. Sorry, the documentation could perhaps be clearer here.

ExternalID is provided by the OS. It is a platform-specific value. You should not set it yourself. Rather, AddOrUpdateEventAsync will populate it for you if it is successful. Then you can grab the ExternalID and store it for later use.

**Comment by Toemsel** [comment]
Thanks for your reply. I see, thanks. In that case, I would recommend to only make the getter public. The setter should be internal. That way it won't be confusing 👍

**Comment by TheAlmightyBob** [comment]
The setter was originally internal. Trying to remember why I changed it... I think I figured there might be certain cases where it might be useful to clear it, such as "copying" an event. I'm not against revisiting that decision though.
